language: python
# command to install dependencies
matrix:
    include:
        - os: linux
          dist: trusty
          python: '2.7'

before_install:
- sudo add-apt-repository ppa:canonical-qt5-edgers/ubuntu1204-qt5 -y
- sudo apt-get update -qq
- sudo apt-get install python-rosbag python-pyqt5 python-pyqt5.qtmultimedia libqt5multimedia5 libqt5glib python-matplotlib python-numpy libav-tools -y -qq
