language: python
# command to install dependencies
before_install:
- sudo apt install rosbag python-pyqt5 python-pyqt5.qtmultimedia libqt5multimedia5 libqt5glib python-matplotlib python-numpy libav-tools
